version: '2'
services:
    schema:
        build:
            context: .
            dockerfile: Dockerfile.migration
        entrypoint: dockerize -wait tcp://mongodb:27017 -timeout 120s
        command: java -jar app.jar -host=mongodb -path=migrations
        volumes:
            - ./samples/:/migrations/
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        command: mongod --smallfiles --logpath=/dev/null --quiet
